#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
02_process_sec_comment_letters_for_fce_iv.py

Purpose
-------
Process SEC-originated comment letters (EDGAR form type UPLOAD) and create
firm-year topic variables used to construct Peer SEC Equity Disclosure
Pressure.

This script is meant to be used AFTER crawling SEC comment letters. It takes:
  1) a metadata CSV for SEC UPLOAD letters, ideally generated by the crawler
     01_crawl_sec_upload_comments.py; and
  2) a directory containing downloaded letter text files.

It outputs:
  - item-level classified comments
  - letter-level classified variables
  - firm-year classified variables suitable for merging back to a firm-year panel

Main idea
---------
The goal is not to classify any SEC comment letter as relevant. The target
topic is SEC disclosure pressure about equity-market access in liquidity,
capital-resources, or financing-constraint settings.

The script classifies comment items into:
  - MD&A / liquidity / capital resources comments
  - equity-market-access comments
  - financing-constraint comments
  - debt-financing comments, used to net out debt-oriented financing pressure

Important notes
---------------
1) This is rule-based text classification. It is transparent and replicable,
   but noisy. Manually validate positive and negative examples before using
   the variable in research.
2) Use peer leave-one-out variables, not the firm's own comments, for the main
   peer pressure variable.
3) Use UPLOAD letters, not CORRESP, for SEC-originated disclosure pressure.

Example
-------
python 02_process_sec_comment_letters_for_fce_iv.py ^
    --letters-csv "output/sec_comment_letter_filing_level.csv" ^
    --text-dir "output/comment_texts" ^
    --outdir "output/topic_classifier" ^
    --firm-id-cols gvkey cik10 ^
    --year-col comment_year

The script tries to be robust to different column names used by the crawler:
  cik/cik10, gvkey, accession/accessionNumber, filing_date_public/filingDate,
  comment_year/filing_year, text_path/filename.
"""

from __future__ import annotations

import argparse
import csv
import logging
import os
import re
import sys
import time
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple


def add_local_deps() -> None:
    here = Path(__file__).resolve()
    for parent in [here.parent, *here.parents]:
        dep_dir = parent / ".codex_pydeps"
        if dep_dir.exists():
            sys.path.insert(0, str(dep_dir))
            return


add_local_deps()

import pandas as pd

try:
    from bs4 import BeautifulSoup
except Exception:  # pragma: no cover
    BeautifulSoup = None


# ---------------------------------------------------------------------------
# Dictionaries
# ---------------------------------------------------------------------------
# These are deliberately conservative. The broad variables keep power, while
# the strict variables require topic + equity + constraint language.

MDA_LIQUIDITY_PATTERNS = [
    r"\bMD&A\b",
    r"\bmanagement['’]?s discussion and analysis\b",
    r"\bitem\s+7\b",
    r"\bliquidity\b",
    r"\bcapital resources\b",
    r"\bcash requirements?\b",
    r"\bcash needs?\b",
    r"\bcapital needs?\b",
    r"\bcash flows?\b",
    r"\boperating cash flows?\b",
    r"\bworking capital\b",
    r"\bsources and uses of cash\b",
    r"\bsources of liquidity\b",
    r"\buses of liquidity\b",
    r"\bfunding\b",
    r"\bfinancing arrangements?\b",
    r"\bknown trends?\b",
    r"\bknown demands?\b",
    r"\bknown commitments?\b",
    r"\bknown uncertainties\b",
    r"\bliquidity and capital resources\b",
]

EQUITY_FINANCING_PATTERNS = [
    r"\bequity financing\b",
    r"\bequity financings\b",
    r"\bequity offering\b",
    r"\bequity offerings\b",
    r"\bpublic offering\b",
    r"\bpublic offerings\b",
    r"\bfollow[- ]on offering\b",
    r"\bregistered offering\b",
    r"\bregistered offerings\b",
    r"\bshelf registration\b",
    r"\bshelf registrations\b",
    r"\bshelf offering\b",
    r"\bshelf offerings\b",
    r"\bat[- ]the[- ]market\b",
    r"\bATM program\b",
    r"\bcommon stock\b",
    r"\bordinary shares\b",
    r"\bcommon shares\b",
    r"\bclass [a-z] common stock\b",
    r"\bsale of shares\b",
    r"\bsales of shares\b",
    r"\bissuance of shares\b",
    r"\bissuances of shares\b",
    r"\bissue shares\b",
    r"\bissued shares\b",
    r"\bissuing shares\b",
    r"\bstock issuance\b",
    r"\bstock issuances\b",
    r"\bshare issuance\b",
    r"\bshare issuances\b",
    r"\bequity securities\b",
    r"\bcapital markets\b",
    r"\braise capital\b",
    r"\braised capital\b",
    r"\braising capital\b",
    r"\bdilution\b",
    r"\bdilutive\b",
    r"\bprivate placement\b",
    r"\bprivate placements\b",
    r"\bconvertible preferred\b",
    r"\bpreferred stock\b",
]

EQUITY_MARKET_ACCESS_PATTERNS = [
    r"\bequity financing\b",
    r"\bequity financings\b",
    r"\bequity offering\b",
    r"\bequity offerings\b",
    r"\bpublic offering\b",
    r"\bpublic offerings\b",
    r"\bfollow[- ]on offering\b",
    r"\bregistered offering\b",
    r"\bregistered offerings\b",
    r"\bshelf registration\b",
    r"\bshelf registrations\b",
    r"\bshelf offering\b",
    r"\bshelf offerings\b",
    r"\bat[- ]the[- ]market\b",
    r"\bATM program\b",
    r"\bsale of shares\b",
    r"\bsales of shares\b",
    r"\bissuance of shares\b",
    r"\bissuances of shares\b",
    r"\bissue shares\b",
    r"\bissued shares\b",
    r"\bissuing shares\b",
    r"\bstock issuance\b",
    r"\bstock issuances\b",
    r"\bshare issuance\b",
    r"\bshare issuances\b",
    r"\bequity securities\b",
    r"\bcapital markets\b",
    r"\braise capital\b",
    r"\braised capital\b",
    r"\braising capital\b",
    r"\bprivate placement\b",
    r"\bprivate placements\b",
]

CONSTRAINT_PATTERNS = [
    r"\bability to obtain\b",
    r"\bability to raise\b",
    r"\bability to access\b",
    r"\baccess to capital\b",
    r"\baccess to the capital markets\b",
    r"\bmay not be able\b",
    r"\bmay be unable\b",
    r"\bunable to\b",
    r"\bcan not\b",
    r"\bcannot\b",
    r"\bdifficulty\b",
    r"\bdifficulties\b",
    r"\badverse market conditions\b",
    r"\bunfavorable market conditions\b",
    r"\bmarket conditions\b",
    r"\blimited access\b",
    r"\blimit our access\b",
    r"\bsufficient liquidity\b",
    r"\binsufficient liquidity\b",
    r"\badditional financing\b",
    r"\badditional capital\b",
    r"\bneed to raise\b",
    r"\bneeds to raise\b",
    r"\bno assurance\b",
    r"\bgoing concern\b",
    r"\bcontinue as a going concern\b",
    r"\bfund our operations\b",
    r"\bfund operations\b",
    r"\bmeet our obligations\b",
    r"\bmeet obligations\b",
    r"\bcash runway\b",
    r"\bsubstantial doubt\b",
]

DEBT_FINANCING_PATTERNS = [
    r"\bdebt\b",
    r"\bborrowings?\b",
    r"\bcredit facility\b",
    r"\bcredit facilities\b",
    r"\bloan agreement\b",
    r"\bloan agreements\b",
    r"\brevolving credit\b",
    r"\brevolver\b",
    r"\bline of credit\b",
    r"\blines of credit\b",
    r"\bcovenants?\b",
    r"\bdefault\b",
    r"\binterest expense\b",
    r"\bmaturity\b",
    r"\bmaturities\b",
    r"\brefinancing\b",
    r"\brefinance\b",
    r"\bsenior notes?\b",
    r"\bbonds?\b",
    r"\bdebentures?\b",
    r"\bsecured notes?\b",
    r"\bunsecured notes?\b",
]

# False-positive filters for equity words. These terms often appear in comments
# about compensation, EPS, fair value, or share-based awards rather than equity
# market access. We do not automatically drop an item, but flag it for audit.
EQUITY_FALSE_POSITIVE_PATTERNS = [
    r"\bshare[- ]based compensation\b",
    r"\bstock[- ]based compensation\b",
    r"\bstock compensation\b",
    r"\boptions? granted\b",
    r"\boption awards?\b",
    r"\bearnings per share\b",
    r"\bbasic EPS\b",
    r"\bdiluted EPS\b",
    r"\btreasury stock method\b",
    r"\bfair value of common stock\b",
]


# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def compile_patterns(patterns: Iterable[str]) -> List[re.Pattern]:
    return [re.compile(p, flags=re.IGNORECASE) for p in patterns]


MDA_LIQUIDITY_RE = compile_patterns(MDA_LIQUIDITY_PATTERNS)
EQUITY_FINANCING_RE = compile_patterns(EQUITY_FINANCING_PATTERNS)
EQUITY_MARKET_ACCESS_RE = compile_patterns(EQUITY_MARKET_ACCESS_PATTERNS)
CONSTRAINT_RE = compile_patterns(CONSTRAINT_PATTERNS)
DEBT_FINANCING_RE = compile_patterns(DEBT_FINANCING_PATTERNS)
EQUITY_FALSE_POSITIVE_RE = compile_patterns(EQUITY_FALSE_POSITIVE_PATTERNS)


def normalize_cik(value) -> str:
    if pd.isna(value):
        return ""
    s = str(value).strip()
    s = re.sub(r"\.0$", "", s)
    s = re.sub(r"\D", "", s)
    return s.zfill(10) if s else ""


def normalize_accession(value) -> str:
    if pd.isna(value):
        return ""
    return str(value).strip()


def accession_nodash(value) -> str:
    return normalize_accession(value).replace("-", "")


def clean_text(raw: str) -> str:
    if raw is None:
        return ""
    text = raw
    if BeautifulSoup is not None and ("<html" in text.lower() or "<document" in text.lower() or "<body" in text.lower()):
        try:
            text = BeautifulSoup(text, "html.parser").get_text(" ", strip=True)
        except Exception:
            pass
    # Remove common EDGAR tags and collapse whitespace.
    text = re.sub(r"<[^>]+>", " ", text)
    text = text.replace("\xa0", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text


def hit_count(text: str, compiled_patterns: List[re.Pattern]) -> int:
    if not text:
        return 0
    return sum(1 for p in compiled_patterns if p.search(text))


def hit_any(text: str, compiled_patterns: List[re.Pattern]) -> int:
    return int(hit_count(text, compiled_patterns) > 0)


def find_hits(text: str, compiled_patterns: List[re.Pattern], max_hits: int = 12) -> str:
    hits: List[str] = []
    for p in compiled_patterns:
        m = p.search(text or "")
        if m:
            hits.append(m.group(0))
            if len(hits) >= max_hits:
                break
    return "; ".join(hits)


def split_comment_items(letter_text: str) -> List[str]:
    """Split SEC comment letter text into approximate numbered comment items.

    SEC letters usually number comments as "1.", "2.", etc. Some letters also
    have repeated section headings. This splitter is intentionally conservative:
    if it cannot find multiple items, it returns the whole letter as one item.
    """
    text = clean_text(letter_text)
    if not text:
        return []

    # Trim boilerplate before the first numbered comment if possible.
    # Keep headings such as "Liquidity and Capital Resources" by cutting only
    # after the first obvious "1." marker.
    first_marker = re.search(r"(?<!\d)(1\.|1\))\s+[A-Z0-9]", text)
    if first_marker and first_marker.start() > 0:
        # Keep a short amount of preceding context because headings may be useful.
        start = max(0, first_marker.start() - 250)
        text_for_split = text[start:]
    else:
        text_for_split = text

    # Split on numbered comment markers. Use a lookahead to keep the marker.
    patterns = [
        r"\s(?=(?:\d{1,3}\.|\d{1,3}\))\s+[A-Z0-9])",
        r"\s(?=(?:Comment\s+\d{1,3}\s*[:.-])\s*)",
    ]
    parts = [text_for_split]
    for pat in patterns:
        trial = re.split(pat, text_for_split, flags=re.IGNORECASE)
        trial = [p.strip() for p in trial if len(p.strip()) >= 60]
        if len(trial) > len(parts):
            parts = trial

    # If the result is still a whole long letter, try splitting on repeated SEC-style headings.
    if len(parts) == 1 and len(parts[0]) > 6000:
        trial = re.split(
            r"\s(?=(?:Form\s+10-K|Form\s+10-Q|Management['’]?s Discussion|Liquidity and Capital Resources|Risk Factors)\b)",
            parts[0],
            flags=re.IGNORECASE,
        )
        trial = [p.strip() for p in trial if len(p.strip()) >= 100]
        if len(trial) > 1:
            parts = trial

    # Remove very short boilerplate and cap extremely long items for efficient output.
    cleaned = []
    seen = set()
    for p in parts:
        p = p.strip()
        if len(p) < 80:
            continue
        key = p[:200]
        if key in seen:
            continue
        seen.add(key)
        cleaned.append(p)

    return cleaned if cleaned else [text]


def window_has_cross_topic(
    text: str,
    left_patterns: List[re.Pattern],
    right_patterns: List[re.Pattern],
    window_chars: int = 900,
) -> int:
    if not text:
        return 0
    right_spans = []
    for p in right_patterns:
        right_spans.extend((m.start(), m.end()) for m in p.finditer(text))
    if not right_spans:
        return 0
    for p in left_patterns:
        for m in p.finditer(text):
            left_start = m.start()
            for right_start, right_end in right_spans:
                if abs(left_start - right_start) <= window_chars or abs(left_start - right_end) <= window_chars:
                    return 1
    return 0


def classify_item(text: str) -> Dict[str, object]:
    liq_score = hit_count(text, MDA_LIQUIDITY_RE)
    eq_score = hit_count(text, EQUITY_FINANCING_RE)
    eq_market_access_score = hit_count(text, EQUITY_MARKET_ACCESS_RE)
    con_score = hit_count(text, CONSTRAINT_RE)
    debt_score = hit_count(text, DEBT_FINANCING_RE)
    eq_false_pos_score = hit_count(text, EQUITY_FALSE_POSITIVE_RE)

    # Core flags
    mda_liq = int(liq_score > 0)
    equity_fin = int(eq_score > 0)
    equity_market_access = int(eq_market_access_score > 0)
    constraint = int(con_score > 0)
    debt_fin = int(debt_score > 0)

    equity_liq_window = window_has_cross_topic(text, EQUITY_MARKET_ACCESS_RE, MDA_LIQUIDITY_RE)
    equity_constraint_window = window_has_cross_topic(text, EQUITY_MARKET_ACCESS_RE, CONSTRAINT_RE)
    common_stock_only = int(equity_fin == 1 and equity_market_access == 0)

    # Broad equity-FCE topic: equity market access language in liquidity/MD&A
    # context, or equity market access language near constraint language.
    eq_fce_broad = int(
        (mda_liq == 1 and equity_market_access == 1)
        or (equity_market_access == 1 and constraint == 1)
        or equity_liq_window == 1
        or equity_constraint_window == 1
    )

    # Strict equity-FCE topic: require both liquidity/capital-resource context
    # and constraint wording, with equity market access language nearby or in
    # the same item.
    eq_fce_strict = int(
        equity_market_access == 1
        and mda_liq == 1
        and constraint == 1
        and (equity_liq_window == 1 or equity_constraint_window == 1 or len(text) <= 3500)
    )

    # Debt-FCE placebo topic.
    debt_fce_broad = int((mda_liq == 1 and debt_fin == 1) or (debt_score >= 2 and constraint == 1))
    debt_fce_strict = int(mda_liq == 1 and debt_fin == 1 and constraint == 1)

    # Equity-specific score. Use this to construct an equity-minus-debt peer pressure measure.
    equity_specific_score = eq_score - debt_score

    # A possible false positive flag: equity terms appear, but only in compensation/EPS context.
    possible_equity_false_positive = int(
        equity_fin == 1
        and (eq_false_pos_score > 0 or common_stock_only == 1)
        and mda_liq == 0
        and constraint == 0
    )

    return {
        "liq_score": liq_score,
        "equity_score": eq_score,
        "equity_market_access_score": eq_market_access_score,
        "constraint_score": con_score,
        "debt_score": debt_score,
        "equity_false_positive_score": eq_false_pos_score,
        "mda_liquidity_comment": mda_liq,
        "equity_financing_comment": equity_fin,
        "equity_market_access_comment": equity_market_access,
        "equity_liq_near_window": equity_liq_window,
        "equity_constraint_near_window": equity_constraint_window,
        "common_stock_only_equity_comment": common_stock_only,
        "constraint_language": constraint,
        "debt_financing_comment": debt_fin,
        "eq_fce_broad_comment": eq_fce_broad,
        "eq_fce_strict_comment": eq_fce_strict,
        "debt_fce_broad_comment": debt_fce_broad,
        "debt_fce_strict_comment": debt_fce_strict,
        "equity_specific_score": equity_specific_score,
        "possible_equity_false_positive": possible_equity_false_positive,
        "liq_hits": find_hits(text, MDA_LIQUIDITY_RE),
        "equity_hits": find_hits(text, EQUITY_FINANCING_RE),
        "equity_market_access_hits": find_hits(text, EQUITY_MARKET_ACCESS_RE),
        "constraint_hits": find_hits(text, CONSTRAINT_RE),
        "debt_hits": find_hits(text, DEBT_FINANCING_RE),
    }


def read_text_file(path: Path) -> str:
    for enc in ("utf-8", "latin-1", "cp1252"):
        try:
            return path.read_text(encoding=enc, errors="ignore")
        except Exception:
            continue
    return ""


def is_raw_pdf_text(text: str) -> bool:
    return (text or "").lstrip().startswith("%PDF")


def guess_col(df: pd.DataFrame, candidates: List[str]) -> Optional[str]:
    lower_map = {c.lower().strip(): c for c in df.columns}
    for cand in candidates:
        if cand.lower().strip() in lower_map:
            return lower_map[cand.lower().strip()]
    # fuzzy contains
    for cand in candidates:
        cand_low = cand.lower().strip()
        for c in df.columns:
            if cand_low in c.lower().strip():
                return c
    return None


def find_text_path(
    row: pd.Series,
    text_dir: Path,
    text_path_col: Optional[str],
    filename_col: Optional[str],
    cik_col: Optional[str],
    accession_col: Optional[str],
    metadata_dir: Optional[Path] = None,
) -> Optional[Path]:
    # Explicit path has priority.
    if text_path_col and pd.notna(row.get(text_path_col)):
        p = Path(str(row.get(text_path_col)))
        if p.exists():
            return p
        if metadata_dir:
            p_meta = metadata_dir / p
            if p_meta.exists():
                return p_meta
        p2 = text_dir / p.name
        if p2.exists():
            return p2

    if filename_col and pd.notna(row.get(filename_col)):
        p = Path(str(row.get(filename_col)))
        if p.exists():
            return p
        if metadata_dir:
            p_meta = metadata_dir / p
            if p_meta.exists():
                return p_meta
        p2 = text_dir / p.name
        if p2.exists():
            return p2

    cik10 = normalize_cik(row.get(cik_col)) if cik_col else ""
    acc = normalize_accession(row.get(accession_col)) if accession_col else ""
    acc_nd = accession_nodash(acc)

    candidates = []
    if cik10 and acc:
        candidates.extend([
            text_dir / f"{cik10}_{acc}.txt",
            text_dir / f"{cik10}_{acc_nd}.txt",
            text_dir / f"{cik10}_{acc}.html",
            text_dir / f"{cik10}_{acc_nd}.html",
        ])
        # Prior crawler used f"{cik10}_{accession}.txt".replace("-", "")
        candidates.append(text_dir / (f"{cik10}_{acc}.txt".replace("-", "")))

    for p in candidates:
        if p.exists():
            return p

    # Last resort: glob accession nodash.
    if acc_nd:
        matches = list(text_dir.glob(f"*{acc_nd}*"))
        if matches:
            return matches[0]
    if acc:
        matches = list(text_dir.glob(f"*{acc}*"))
        if matches:
            return matches[0]

    return None


def build_metadata_from_text_dir(text_dir: Path) -> pd.DataFrame:
    rows = []
    for p in sorted(text_dir.glob("*.txt")) + sorted(text_dir.glob("*.html")):
        name = p.name
        # Try common format cik_accession.txt, with dashes removed or present.
        m = re.match(r"(?P<cik>\d{10})[_-](?P<acc>[0-9\-]+)", name)
        cik10 = m.group("cik") if m else ""
        acc = m.group("acc") if m else p.stem
        rows.append({"cik10": cik10, "accession": acc, "text_path": str(p)})
    return pd.DataFrame(rows)


def safe_to_csv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False, quoting=csv.QUOTE_MINIMAL)


def format_duration(seconds: float) -> str:
    seconds = max(0, int(seconds))
    hours, rem = divmod(seconds, 3600)
    minutes, secs = divmod(rem, 60)
    if hours:
        return f"{hours}h {minutes:02d}m {secs:02d}s"
    if minutes:
        return f"{minutes}m {secs:02d}s"
    return f"{secs}s"


def process_letters(args: argparse.Namespace) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    text_dir = Path(args.text_dir)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    metadata_dir = None
    if args.letters_csv:
        letters_csv = Path(args.letters_csv)
        metadata_dir = letters_csv.parent
        meta = pd.read_csv(letters_csv, dtype=str)
    else:
        meta = build_metadata_from_text_dir(text_dir)

    if meta.empty:
        raise RuntimeError("No metadata rows found. Provide --letters-csv or a non-empty --text-dir.")

    cik_col = guess_col(meta, ["cik10", "cik", "CIK"])
    gvkey_col = guess_col(meta, ["gvkey", "GVKEY"])
    accession_col = guess_col(meta, ["accession", "accessionNumber", "accession_number", "accession no"])
    year_col = args.year_col if args.year_col in meta.columns else guess_col(meta, ["comment_year", "filing_year", "year"])
    date_col = guess_col(meta, ["filing_date_public", "filingDate", "filing_date", "date", "acceptedDateTime"])
    form_col = guess_col(meta, ["form", "form_type", "Form Type"])
    text_path_col = guess_col(meta, ["text_file", "text_path", "filepath", "file_path", "path"])
    filename_col = guess_col(meta, ["filename", "primary_doc", "primaryDocument", "file_name"])
    url_col = guess_col(meta, ["url", "filing_url", "document_url"])
    source_doc_type_col = guess_col(meta, ["source_doc_type", "doc_type", "document_type"])
    extraction_method_col = guess_col(meta, ["extraction_method", "text_extraction_method"])
    extraction_error_col = guess_col(meta, ["text_extraction_error", "extraction_error"])
    text_starts_raw_pdf_col = guess_col(meta, ["text_starts_raw_pdf", "raw_pdf_text"])

    logging.info("Column mapping: cik=%s gvkey=%s accession=%s year=%s date=%s form=%s text_path=%s filename=%s",
                 cik_col, gvkey_col, accession_col, year_col, date_col, form_col, text_path_col, filename_col)

    if args.limit is not None:
        meta = meta.head(args.limit).copy()

    item_rows: List[Dict[str, object]] = []
    letter_rows: List[Dict[str, object]] = []
    missing_text = 0
    empty_text = 0
    raw_pdf_text = 0
    started_at = time.time()
    total_rows = len(meta)

    for idx, row in meta.iterrows():
        if form_col and str(row.get(form_col, "")).upper() not in ("", "UPLOAD") and not args.keep_non_upload:
            continue

        text_path = find_text_path(row, text_dir, text_path_col, filename_col, cik_col, accession_col, metadata_dir)
        if text_path is None:
            missing_text += 1
            continue

        raw_text = read_text_file(text_path)
        if is_raw_pdf_text(raw_text):
            raw_pdf_text += 1
            msg = f"Raw PDF bytes detected in text file; rerun crawler with PDF extraction: {text_path}"
            if not args.allow_raw_pdf_text:
                raise RuntimeError(msg)
            logging.warning(msg)
        text = clean_text(raw_text)
        if not text:
            empty_text += 1
            if args.drop_empty_text:
                continue
        items = split_comment_items(text)

        cik10 = normalize_cik(row.get(cik_col)) if cik_col else ""
        gvkey = row.get(gvkey_col) if gvkey_col else ""
        accession = normalize_accession(row.get(accession_col)) if accession_col else text_path.stem
        url = row.get(url_col) if url_col else ""

        comment_year = None
        if year_col and pd.notna(row.get(year_col)):
            try:
                comment_year = int(float(str(row.get(year_col))))
            except Exception:
                comment_year = None
        if comment_year is None and date_col and pd.notna(row.get(date_col)):
            dt = pd.to_datetime(row.get(date_col), errors="coerce")
            if pd.notna(dt):
                comment_year = int(dt.year)

        base = {
            "source_row": idx,
            "gvkey": gvkey,
            "cik10": cik10,
            "accession": accession,
            "comment_year": comment_year,
            "filing_date_public": row.get(date_col) if date_col else "",
            "form": row.get(form_col) if form_col else "UPLOAD",
            "url": url,
            "text_file": str(text_path),
            "source_doc_type": row.get(source_doc_type_col) if source_doc_type_col else "",
            "extraction_method": row.get(extraction_method_col) if extraction_method_col else "",
            "text_extraction_error": row.get(extraction_error_col) if extraction_error_col else "",
            "text_starts_raw_pdf": row.get(text_starts_raw_pdf_col) if text_starts_raw_pdf_col else int(is_raw_pdf_text(raw_text)),
            "letter_text_length": len(text),
            "n_comment_items_detected": len(items),
        }

        # Classify each item.
        letter_agg: Dict[str, object] = dict(base)
        sum_cols = [
            "liq_score", "equity_score", "constraint_score", "debt_score",
            "equity_false_positive_score", "mda_liquidity_comment",
            "equity_financing_comment", "equity_market_access_comment",
            "equity_liq_near_window", "equity_constraint_near_window",
            "common_stock_only_equity_comment",
            "constraint_language", "debt_financing_comment",
            "eq_fce_broad_comment", "eq_fce_strict_comment",
            "debt_fce_broad_comment", "debt_fce_strict_comment",
            "equity_specific_score", "possible_equity_false_positive",
        ]
        for c in sum_cols:
            letter_agg[f"n_{c}"] = 0

        for item_id, item in enumerate(items, start=1):
            cls = classify_item(item)
            out = dict(base)
            out.update(cls)
            out["comment_item_id"] = item_id
            out["comment_item_length"] = len(item)
            # Store full text optionally; otherwise store a short excerpt for validation.
            out["comment_text_excerpt"] = item[: args.excerpt_chars]
            if args.save_full_item_text:
                out["comment_text_full"] = item
            item_rows.append(out)
            for c in sum_cols:
                letter_agg[f"n_{c}"] += int(cls.get(c, 0))

        # Letter-level dummies.
        for c in [
            "mda_liquidity_comment", "equity_financing_comment", "equity_market_access_comment",
            "equity_liq_near_window", "equity_constraint_near_window",
            "common_stock_only_equity_comment", "constraint_language",
            "debt_financing_comment", "eq_fce_broad_comment", "eq_fce_strict_comment",
            "debt_fce_broad_comment", "debt_fce_strict_comment",
            "possible_equity_false_positive",
        ]:
            letter_agg[f"own_{c}"] = int(letter_agg.get(f"n_{c}", 0) > 0)

        # Letter-level topic combinations. These retain power when SEC places
        # liquidity and equity-market-access comments in separate numbered
        # items within the same letter.
        letter_agg["own_eq_fce_letter_broad_comment"] = int(
            letter_agg["own_mda_liquidity_comment"] == 1
            and letter_agg["own_equity_market_access_comment"] == 1
        )
        letter_agg["own_eq_fce_letter_strict_comment"] = int(
            letter_agg["own_mda_liquidity_comment"] == 1
            and letter_agg["own_equity_market_access_comment"] == 1
            and letter_agg["own_constraint_language"] == 1
        )
        letter_agg["own_eq_fce_any_broad_comment"] = int(
            letter_agg["own_eq_fce_broad_comment"] == 1
            or letter_agg["own_eq_fce_letter_broad_comment"] == 1
        )
        letter_agg["own_eq_fce_any_strict_comment"] = int(
            letter_agg["own_eq_fce_strict_comment"] == 1
            or letter_agg["own_eq_fce_letter_strict_comment"] == 1
        )

        letter_rows.append(letter_agg)

        if args.progress_every > 0 and len(letter_rows) % args.progress_every == 0:
            elapsed = time.time() - started_at
            pct = 100.0 * len(letter_rows) / total_rows if total_rows else 100.0
            eta = elapsed / len(letter_rows) * (total_rows - len(letter_rows)) if letter_rows else 0
            logging.info(
                "Processed %d/%d metadata rows (%.1f%%), item rows=%d, elapsed=%s, ETA=%s",
                len(letter_rows), total_rows, pct, len(item_rows), format_duration(elapsed), format_duration(eta)
            )

    if missing_text:
        logging.warning("Missing text files for %s metadata rows.", missing_text)
    if empty_text:
        logging.warning("Empty text files for %s metadata rows.", empty_text)
    if raw_pdf_text:
        logging.warning("Raw PDF text files encountered: %s", raw_pdf_text)

    items_df = pd.DataFrame(item_rows)
    letters_df = pd.DataFrame(letter_rows)

    if letters_df.empty:
        raise RuntimeError("No letters were processed. Check --letters-csv and --text-dir.")

    # Firm-year collapse. Keep both dummies and counts. Use CIK-year as the primary unit;
    # include gvkey if available and unique.
    group_cols = ["cik10", "comment_year"]
    if "gvkey" in letters_df.columns and letters_df["gvkey"].notna().any():
        # Keep gvkey only if it does not create too many duplicate mappings; otherwise CIK-year is safer.
        pass

    agg_dict = {
        "accession": "count",
        "n_comment_items_detected": "sum",
        "letter_text_length": "sum",
    }
    if "gvkey" in letters_df.columns:
        agg_dict["gvkey"] = "first"
    count_cols = [c for c in letters_df.columns if c.startswith("n_")]
    own_cols = [c for c in letters_df.columns if c.startswith("own_")]
    for c in count_cols:
        agg_dict[c] = "sum"
    for c in own_cols:
        agg_dict[c] = "max"

    fy = letters_df.groupby(group_cols, dropna=False).agg(agg_dict).reset_index()
    fy = fy.rename(columns={
        "accession": "n_upload_letters",
        "n_comment_items_detected": "n_upload_items_detected",
        "letter_text_length": "total_upload_text_length",
    })

    # Rename key variables to concise Stata-friendly names.
    rename_map = {
        "own_mda_liquidity_comment": "own_liq_mda_comment",
        "own_equity_financing_comment": "own_equityfin_comment",
        "own_equity_market_access_comment": "own_equity_market_access_comment",
        "own_eq_fce_broad_comment": "own_eq_fce_broad_comment",
        "own_eq_fce_strict_comment": "own_eq_fce_strict_comment",
        "own_eq_fce_letter_broad_comment": "own_eq_fce_letter_broad_comment",
        "own_eq_fce_letter_strict_comment": "own_eq_fce_letter_strict_comment",
        "own_eq_fce_any_broad_comment": "own_eq_fce_any_broad_comment",
        "own_eq_fce_any_strict_comment": "own_eq_fce_any_strict_comment",
        "own_debt_fce_broad_comment": "own_debt_fce_broad_comment",
        "own_debt_fce_strict_comment": "own_debt_fce_strict_comment",
        "n_mda_liquidity_comment": "n_liq_mda_comment_items",
        "n_equity_financing_comment": "n_equityfin_comment_items",
        "n_equity_market_access_comment": "n_equity_market_access_items",
        "n_common_stock_only_equity_comment": "n_commonstk_only_eq_comment",
        "own_equity_constraint_near_window": "own_eq_constraint_window",
        "own_common_stock_only_equity_comment": "own_commonstk_only_eq_comment",
        "own_possible_equity_false_positive": "own_poss_eq_falsepos",
        "n_eq_fce_broad_comment": "n_eq_fce_broad_comment_items",
        "n_eq_fce_strict_comment": "n_eq_fce_strict_comment_items",
        "n_debt_fce_broad_comment": "n_debt_fce_broad_comment_items",
        "n_debt_fce_strict_comment": "n_debt_fce_strict_comment_items",
    }
    letters_df = letters_df.rename(columns=rename_map)
    fy = fy.rename(columns=rename_map)

    for df in (items_df, letters_df, fy):
        if "cik10" in df.columns:
            df["cik10"] = df["cik10"].apply(normalize_cik)
        if "gvkey" in df.columns:
            df["gvkey"] = df["gvkey"].astype(str).str.replace(r"\.0$", "", regex=True).str.zfill(6)

    # Equity-minus-debt topic pressure at firm-year level.
    if {"n_eq_fce_broad_comment_items", "n_debt_fce_broad_comment_items"}.issubset(fy.columns):
        fy["n_eq_minus_debt_fce_broad_items"] = fy["n_eq_fce_broad_comment_items"] - fy["n_debt_fce_broad_comment_items"]
    if {"own_eq_fce_broad_comment", "own_debt_fce_broad_comment"}.issubset(fy.columns):
        fy["own_eq_minus_debt_fce_broad"] = fy["own_eq_fce_broad_comment"] - fy["own_debt_fce_broad_comment"]
    if {"own_eq_fce_any_broad_comment", "own_debt_fce_broad_comment"}.issubset(fy.columns):
        fy["own_eq_any_minus_debt_fce_broad"] = fy["own_eq_fce_any_broad_comment"] - fy["own_debt_fce_broad_comment"]
    if {"n_eq_fce_strict_comment_items", "n_debt_fce_strict_comment_items"}.issubset(fy.columns):
        fy["n_eq_minus_debt_fce_strict_items"] = fy["n_eq_fce_strict_comment_items"] - fy["n_debt_fce_strict_comment_items"]

    safe_to_csv(items_df, outdir / "sec_comment_items_fce_topic_classified.csv")
    safe_to_csv(letters_df, outdir / "sec_comment_letters_fce_topic_classified.csv")
    safe_to_csv(fy, outdir / "sec_comment_firmyear_fce_topic.csv")

    # Validation samples for manual review.
    if args.validation_sample_n > 0 and not items_df.empty:
        flagged_cols = [
            "eq_fce_broad_comment", "eq_fce_strict_comment",
            "debt_fce_broad_comment", "mda_liquidity_comment",
            "possible_equity_false_positive",
        ]
        for c in flagged_cols:
            if c in items_df.columns:
                sub = items_df[items_df[c] == 1].sample(
                    n=min(args.validation_sample_n, int((items_df[c] == 1).sum())),
                    random_state=args.seed,
                ) if int((items_df[c] == 1).sum()) > 0 else pd.DataFrame()
                if not sub.empty:
                    safe_to_csv(sub, outdir / f"validation_sample_{c}.csv")

        # Also a random negative sample.
        neg_cond = (items_df.get("eq_fce_broad_comment", 0) == 0)
        neg = items_df[neg_cond].sample(n=min(args.validation_sample_n, int(neg_cond.sum())), random_state=args.seed) if int(neg_cond.sum()) > 0 else pd.DataFrame()
        if not neg.empty:
            safe_to_csv(neg, outdir / "validation_sample_eq_fce_negative.csv")

    return items_df, letters_df, fy


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Classify SEC UPLOAD comment letters into equity-focused FCE-related topics."
    )
    parser.add_argument("--letters-csv", default="", help="Metadata CSV for downloaded SEC UPLOAD letters.")
    parser.add_argument("--text-dir", required=True, help="Directory containing downloaded letter text/html files.")
    parser.add_argument("--outdir", required=True, help="Output directory.")
    parser.add_argument("--year-col", default="comment_year", help="Year column in metadata CSV if available.")
    parser.add_argument("--firm-id-cols", nargs="*", default=["gvkey", "cik10"], help="Documentation only; IDs are auto-detected.")
    parser.add_argument("--keep-non-upload", action="store_true", help="Do not drop non-UPLOAD rows if a form column exists.")
    parser.add_argument("--excerpt-chars", type=int, default=1500, help="Number of characters from each item to keep in excerpt.")
    parser.add_argument("--save-full-item-text", action="store_true", help="Save full comment item text in item-level CSV. Large file.")
    parser.add_argument("--validation-sample-n", type=int, default=100, help="Number of items per validation sample.")
    parser.add_argument("--seed", type=int, default=20260601, help="Random seed for validation samples.")
    parser.add_argument("--log-file", default="", help="Optional log file path.")
    parser.add_argument("--limit", type=int, default=None, help="Optional number of metadata rows to process for testing.")
    parser.add_argument("--progress-every", type=int, default=5000, help="Print progress every N processed letters.")
    parser.add_argument("--drop-empty-text", action="store_true", help="Drop rows whose resolved text file is empty.")
    parser.add_argument(
        "--allow-raw-pdf-text",
        action="store_true",
        help="Allow text files that still begin with %%PDF. Default is to stop because PDF extraction failed.",
    )
    return parser.parse_args(argv)


def setup_logging(log_file: str = "") -> None:
    handlers: List[logging.Handler] = [logging.StreamHandler(sys.stdout)]
    if log_file:
        Path(log_file).parent.mkdir(parents=True, exist_ok=True)
        handlers.append(logging.FileHandler(log_file, encoding="utf-8"))
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=handlers,
    )


def main(argv: Optional[List[str]] = None) -> None:
    args = parse_args(argv)
    setup_logging(args.log_file)
    logging.info("Starting SEC comment-letter FCE topic classification.")
    items, letters, fy = process_letters(args)
    logging.info("Processed %d comment items, %d letters, %d firm-years.", len(items), len(letters), len(fy))
    logging.info("Outputs saved to: %s", args.outdir)

    # Print summary counts.
    key_cols = [
        "own_liq_mda_comment",
        "own_equityfin_comment",
        "own_equity_market_access_comment",
        "own_eq_fce_broad_comment",
        "own_eq_fce_strict_comment",
        "own_eq_fce_letter_broad_comment",
        "own_eq_fce_letter_strict_comment",
        "own_eq_fce_any_broad_comment",
        "own_eq_fce_any_strict_comment",
        "own_debt_fce_broad_comment",
        "own_debt_fce_strict_comment",
    ]
    for c in key_cols:
        if c in fy.columns:
            logging.info("Firm-year share %s = %.4f", c, fy[c].fillna(0).mean())


if __name__ == "__main__":
    main()
